# Generated by Django 4.1.5 on 2023-03-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_remove_urun_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='fiyat',
        ),
    ]
