# Generated by Django 4.1.5 on 2023-03-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0004_remove_urun_fiyat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('aciklama', models.TextField(max_length=1000)),
                ('fiyat', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Urun',
        ),
    ]
