# Generated by Django 4.1.5 on 2023-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_urunler_delete_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='resim',
            field=models.FileField(null=True, upload_to='urunler/'),
        ),
    ]
